version: "3.8"

networks:
  bridge-net:
    name: api-bridge

services:
  api-discovery:
    container_name: discovery-app
    image: sarathvedha/backend-registry-app:latest
    environment:
      APP_PROFILE: prod
      APP_PORT: 8061
      LOG_PATH: /app/log
      SERVICE_URL: http://api-discovery:8061
    ports:
      - 8061:8061
    restart: on-failure
    networks:
      bridge-net:

  api-config:
    container_name: config-app
    image: sarathvedha/backend-config-app:latest
    depends_on:
      - "api-discovery"
    environment:
      APP_PROFILE: prod
      APP_PORT: 8092
      LOG_PATH: /app/log
      GIT_URL: https://github.com/SarathVedha/api-configs.git
      GIT_BRANCH: master
      GIT_PATH: /
      BASE_CONFIG_PATH: configs
      SERVICE_URL: http://api-discovery:8061
    ports:
      - 8092:8092
    restart: on-failure
    networks:
      bridge-net:

  api-gateway:
    container_name: gateway-app
    image: sarathvedha/backend-gateway-app:latest
    depends_on:
      - "api-config"
      - "api-discovery"
    environment:
      APP_PROFILE: prod
      CONFIG_URL: http://api-config:8092
      GIT_BRANCH: master
      APP_PORT: 80
      LOG_PATH: /app/log
      SERVICE_HOSTNAME: api-discovery
      SERVICE_URL: http://api-discovery:8061
    ports:
      - 80:80
    restart: on-failure
    networks:
      bridge-net:
  
  api-backend:
    container_name: api-app
    image: sarathvedha/backend-app:latest
    depends_on:
      - "api-config"
      - "api-discovery"
      - "api-gateway"
    environment:
      APP_PROFILE: prod
      CONFIG_URL: http://api-config:8092
      GIT_BRANCH: master
      APP_PORT: 8080
      LOG_PATH: /app/log
      SERVICE_HOSTNAME: api-discovery
      SERVICE_URL: http://api-discovery:8061
      API_DELAY: "2"
      API_PATH: /app/apis
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      bridge-net: