apiVersion: v1
kind: Namespace
metadata:
  name: dev
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-app-sa # Createing service account for admin service to access dev namespace apis
  namespace: dev

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-app-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-app-role-bind
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: api-app-sa
    namespace: dev
roleRef:
  kind: ClusterRole
  name: api-app-role
  apiGroup: rbac.authorization.k8s.io