server:
  port: ${APP_PORT}

spring:
  application:
    name: ADMIN_SERVER
  output:
    ansi:
      enabled: always
  boot:
    admin:
      ui:
        title: API ADMIN SERVER
  cloud:
    kubernetes:
      discovery:
        service-labels:
          spring-boot: true
        namespaces: ${NAME_SPACES}
#        all-namespaces: true
      reload:
        enabled: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, ${spring.profiles.active}]'
  file:
    name: ${LOG_PATH:.}/api-admin-app.log

info:
  app:
    name: ${spring.application.name}
    description: APIs Admin Service
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom