server:
  port: 8070

spring:
  output:
    ansi:
      enabled: always
  application:
    name: ADMIN_SERVER

#eureka:
#  client:
#    service-url:
#      defaultZone: ${SERVICE_URL}

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, ${spring.profiles.active}]'

info:
  app:
    name: ${spring.application.name}
    description: APIs Admin Service
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom