server:
  port: 8050

spring:
  application:
    name: API-REGISTRY
  output:
    ansi:
      enabled: always

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, ${spring.profiles.active}]'

info:
  app:
    name: ${spring.application.name}
    description: APIs Service Registry
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom